version: "3.8"

services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}
    volumes:
      - mongodb_data:/data/db
    command: ["--wiredTigerCacheSizeGB", "0.25"]

volumes:
  mongodb_data: